project:
  output-dir: docs
  type: website

website:
  twitter-card: true
  open-graph: true
  image: "assets/img/featured.png"
  favicon: "assets/img/favicon.ico"

format:
  dashboard:
    theme: [flatly, assets/css/custom.scss]
    orientation: columns
    include-in-header: assets/html/fontawesome.html
    include-after-body: assets/html/footer.html
    fig-align: left

execute:
  echo: false
  eval: true
  warning: false
  message: false
