---
title: ScotRail Performance
---

```{r}
# Read in data and load packages
library(tidyverse)
library(reactable)
library(reactablefmtr)
library(ggplot2)
library(ggtext)
library(ggiraph)
library(glue)
library(showtext)
daily_data <- readr::read_csv("data/daily_data.csv")
monthly_data <- readr::read_csv("data/monthly_data.csv")
monthly_data_stations <- readr::read_csv("data/monthly_data_stations.csv")
today_date <- daily_data |>
  slice_max(date) |>
  pull(date)
today_month <- monthly_data |>
  slice_max(date) |>
  pull(date)
bg_col <- "#F2F4F8"
font_add_google("Nunito")
body_font <- "Nunito"
```


# Daily 

## Column {width="40%"}

::: {.card height="10%" expandable=false padding=0px}

```{r}
#| output: asis
d <- format(as.Date(today_date), "%A %e %B %Y")
cat(paste0("<h2>", d, "</h2>"))
```

:::

### Row

```{r}
#| component: valuebox
#| title: Arriving within 5 minutes
perc_ppm <- daily_data |>
  slice_max(date) |>
  pull(PPM) |>
  paste0("%")
list(
  icon = "stopwatch",
  color = "primary",
  value = perc_ppm
)
```

### Row

```{r}
#| component: valuebox
#| title: Unplanned cancellations
num_unplanned <- daily_data |>
  slice_max(date) |>
  pull(`Number of unplanned cancellations`)
list(
  icon = "x-circle",
  color = "secondary",
  value = num_unplanned
)
```

### Row

```{r}
#| component: valuebox
#| title: Previous day train crew absences
num_absent <- daily_data |>
  slice_max(date) |>
  pull(`Previous day traincrew absences`)
list(
  icon = "person-dash",
  color = "secondary",
  value = num_absent
)
```

## Column {width="60%"}

::: {.card height="75%" expandable=false}

::: {.panel-tabset} 

## Punctuality

```{r}
#| expandable: false
#| fig-align: left
#| fig-alt: "Line chart showing the percentage of trains arriving within 5 minutes of advertised time per day across the ScotRail network. The data is available to download from the link beneath the chart."
line_chart_data <- daily_data |>
  mutate(
    below = if_else(
      PPM < 92.5, "(below target)", ""
    ),
    label = glue('<b>{format(as.Date(date), "%A %e %B, %Y")}</b><br>{PPM}% {below}')
  )
g_int <- ggplot(
  data = line_chart_data,
  mapping = aes(x = date, y = PPM)
) +
  geom_line() +
  geom_hline(yintercept = 92.5, colour = "#e74c3c") +
  geom_point_interactive(
    mapping = aes(tooltip = label, data_id = date),
    colour = bg_col,
    alpha = 0,
    size = 5
  ) +
  labs(
    subtitle = "Percentage of trains that arrive at their destination within five minutes of the advertised time",
    x = NULL, y = NULL
  ) +
  scale_y_continuous(limits = c(NA, 100)) +
  coord_cartesian(expand = FALSE, clip = "off") +
  theme_minimal(base_size = 15, base_family = body_font) +
  theme(
    plot.background = element_rect(
      fill = bg_col, colour = bg_col
    ),
    plot.subtitle = element_textbox_simple(
      margin = ggplot2::margin(t = 5, b = 10)
    ),
    plot.title.position = "plot"
  )
girafe(
  ggobj = g_int,
  bg = bg_col,
  width_svg = 7,
  height_svg = 5,
  options = list(
    opts_tooltip(
      css = "
        padding: 5pt;
        font-size: 1rem;
        background-color: #DADFE7;
        border-radius: 3px;
        line-height: 1;
        color: #0E1116;"
    ),
    opts_hover(css = "opacity:0;"),
    opts_toolbar(saveaspng = FALSE, hidden = c("saveaspng", "fullscreen")),
    opts_zoom(max = 1),
    opts_sizing(rescale = TRUE, width = 1)
  )
)
```

## Cancellations {expandable=false}

```{r}
#| expandable: false
#| fig-align: left
#| fig-alt: "Bar chart showing the number of planned and unplanned cancellations per day across the ScotRail network. The data is available to download from the link beneath the chart."
bar_chart_data <- daily_data |>
  select(date, `Number of planned cancellations`, `Number of unplanned cancellations`) |>
  mutate(total = `Number of unplanned cancellations` + `Number of planned cancellations`) |>
  mutate(
    label = glue('<b>{format(as.Date(date), "%A %e %B, %Y")}</b><br>Planned: {`Number of planned cancellations`}<br>Unplanned: {`Number of unplanned cancellations`}<br>Total: {total}')
  )
bar_chart_data2 <- bar_chart_data |>
  select(-c(total, label)) |>
  pivot_longer(-date)
g_int <- ggplot(
  data = bar_chart_data2,
  mapping = aes(
    x = date, y = value,
    fill = str_to_sentence(str_remove(name, "Number of "))
  )
) +
  geom_col(colour = "transparent", width = 0.85) +
  geom_col_interactive(
    data = bar_chart_data,
    mapping = aes(x = date, y = total, tooltip = label, data_id = date),
    fill = "transparent",
    colour = "transparent",
    width = 0.85
  ) +
  scale_fill_manual(values = c("#707c7d", "#2c3e50")) +
  labs(
    subtitle = "Number of cancellations",
    x = NULL, y = NULL
  ) +
  coord_cartesian(expand = FALSE, clip = "off") +
  theme_minimal(base_size = 15, base_family = body_font) +
  theme(
    plot.background = element_rect(
      fill = bg_col, colour = bg_col
    ),
    plot.subtitle = element_textbox_simple(
      margin = ggplot2::margin(t = 5, b = 10)
    ),
    plot.title.position = "plot",
    legend.position = "bottom",
    legend.title = element_blank()
  )
girafe(
  ggobj = g_int,
  bg = bg_col,
  width_svg = 7,
  height_svg = 5,
  options = list(
    opts_tooltip(
      css = "
        padding: 5pt;
        font-size: 1rem;
        background-color: #DADFE7;
        border-radius: 3px;
        line-height: 1;
        color: #0E1116;"
    ),
    opts_hover(css = "fill:#3498db;"),
    opts_toolbar(saveaspng = FALSE, hidden = c("saveaspng", "fullscreen")),
    opts_zoom(max = 1),
    opts_sizing(rescale = TRUE, width = 1)
  )
)
```

:::

:::

::: {.card height="25%" expandable=false padding=0px}

```{=html}
<div class="link-buttons" style="display: flex; gap: 10px;">
  <a href="data/daily_data.csv" class="icon-link" target="_blank" rel="noopener"><i class="fa-solid fa-download"></i>Data</a>
  <button class="icon-link" command="show-modal" commandfor="notes-1"><i class="fa-solid fa-note-sticky"></i>Notes</button>
</div>

<dialog id="notes-1" class="notes-modal">
  <ol>
  <li>ScotRail's target for the entire network is for 92.5% of services to arrive at their destination within five minutes of the advertised time, indicated by the red line on the chart.</li>
  <li>When a specially advertised revised timetable is in operation, e.g., for times of engineering work, performance is measured against the revised times.</li>
</ol>
  <button commandfor="notes-1" command="close" class="modal-close">x</button>
</dialog>
```

:::


# Monthly

## Column {width="40%"}

::: {.card height="10%" expandable=false padding=0px}

```{r}
#| output: asis
d <- format(as.Date(today_month), "%B %Y")
cat(paste0("<h2>", d, "</h2>"))
```

:::


### Row

```{r}
#| component: valuebox
#| title: Arriving within 5 minutes
perc_perf <- monthly_data |>
  filter(date == today_month) |>
  pull(perf) |>
  paste0("%")
list(
  icon = "stopwatch",
  color = "primary",
  value = perc_perf
)
```

### Row

```{r}
#| component: valuebox
#| title: Change from previous month
comp_perf <- monthly_data |>
  filter(date == today_month) |>
  pull(comparison)
list(
  icon = "graph-up-arrow",
  color = "secondary",
  value = comp_perf
)
```

### Row

```{r}
#| component: valuebox
#| title: Worst performing terminus
worst_station <- monthly_data_stations |>
  filter(date == today_month) |>
  slice_min(STPM) |>
  pull(Location)
list(
  icon = "trophy-fill",
  color = "secondary",
  value = worst_station
)
```

## Column {width="60%"}

::: {.card height="75%" expandable=false}

```{r}
#| expandable: false
monthly_data_stations %>%
  mutate(
    STPM_fill = case_when(
      STPM >= 92.5 ~ "#92c5de",
      STPM < 92.5 & STPM >= 85 ~ "#f4a582",
      STPM < 92.5 & STPM >= 0 ~ "#b2182b",
      TRUE ~ "white"
    ),
    STPM = if_else(is.na(STPM), "", as.character(STPM))
  ) %>%
  select(Location, STPM, STPM_fill, On_Time_A, On_Time_T) %>%
  reactable(
    columns = list(
      STPM = colDef(
        cell = color_tiles(
          data = .,
          color_ref = "STPM_fill"
        ),
        name = "% arriving within 5 mins",
      ),
      STPM_fill = colDef(show = FALSE),
      On_Time_A = colDef(
        name = "% arrivals within 59s"
      ),
      On_Time_T = colDef(
        name = "% terminations within 59s"
      )
    ),
    searchable = TRUE,
    defaultPageSize = 6
  )
```

:::

::: {.card expandable=false padding=0px}

```{=html}
<div class="link-buttons" style="display: flex; gap: 10px;">
  <a href="data/monthly_data_stations.csv" class="icon-link" target="_blank" rel="noopener"><i class="fa-solid fa-download"></i>Data</a>
  <button class="icon-link" command="show-modal" commandfor="notes-2"><i class="fa-solid fa-note-sticky"></i>Notes</button>
</div>

<dialog id="notes-2" class="notes-modal">
  <ol>
  <li>The table shows the arrival times at terminal stations on the ScotRail network over a rolling 12 months.</li>
</ol>
  <button commandfor="notes-2" command="close" class="modal-close">x</button>
</dialog>


```

:::




